### ISSUE TITLE
How to create a text SVG of a specified size?

### ISSUE THREAD

**Issue by StringKe** [foliojs/fontkit#220]
`font.layout("hello").glyphs[0].path.toSVG()` 
It's too big. How do I set the font size and generate SVG?

**Comment by Pomax** [comment]
What do you mean "it's too big"? SVG are scalable graphics: you can fit them to any size simply by scaling the whole thing to fit whatever box it needs to go into.

**Comment by StringKe** [comment]
> What do you mean "it's too big"? SVG is unitless: a 1000x1000 SVG is not "pixels", it's just "1000 units, proportional to the unit value that the vectors use". Hence the Scalable Vector Graphics name.
> 
> You can fit an SVG to any size you need by simply scaling the whole thing to fit whatever box it needs to go into (via CSS, typesetting box commands, etc).

For example, how wide is a 12px pixel font?

**Comment by Pomax** [comment]
That question _literally_ has no answer in real typography other than "measure it after typesetting it" (e.g. what typesetting software like LaTeX or InDesign do).

Fonts do not have a "size" other than their em quad size, so if you ask Fontkit to export text as SVG, you're going to get vector graphics back that _you_ can then resize to fit whatever space _you_ need it to fit into. 

If the SVG is too big, scale it down. That's exactly what SVG is for. However, note that if you want things scale to tiny sizes, like 12pt, you do _not_ want SVG at all. You want to tell the font to render itself to that size because it might have [bitmap strike data](https://docs.microsoft.com/en-us/typography/opentype/spec/sbix) that is optimized for the exact point/pixel size you need the text shaped at, because scaling down to small point sizes is [really, really, REALLY hard](http://rastertragedy.com/).

**Comment by StringKe** [comment]
I see that the font size can be set in `pdfkit`. I tried to find the corresponding method in this package, but there was no result.
